# Bodies of the three Quaesitor texts. Executed by quaesitor_texts.py (page(), c(), grid in scope).

# ---------------- 1 · measurements ----------------
page("measurements", 1,
     "Same score, opposite characters — Quaesitor",
     "Two frontier models, the same number of right answers, opposite failure behaviour. What happened when a warehouse assistant was asked 26 questions with a known answer, in fifteen languages, on five warehouses.",
     f'''
<header class="text-head">
  <p class="kicker">Quaesitor · 1 of 3 · measurements · 2026</p>
  <h1>Same score, <em>opposite characters</em></h1>
  <p class="deck">I put two frontier models in front of a warehouse, asked them 26 questions I already knew the answers to, and counted. They got the same number right. Everything else about them was different.</p>
  <dl class="facts">
    <div><dt>measured answers</dt><dd>5 790 <small>15 languages · 5 warehouses · Aug 2026</small></dd></div>
    <div><dt>retail pack, declined</dt><dd>55 vs 1 <small>same questions, same correct count</small></dd></div>
    <div><dt>with documentation</dt><dd>2 / 26 → 2 / 26 <small>correct answers, unchanged</small></dd></div>
    <div><dt>median error with docs</dt><dd>72 % → 23 % <small>smaller, not rarer</small></dd></div>
  </dl>
</header>

<section>
<p>A silent failure is an answer that runs without error, looks plausible and is wrong, with nothing downstream to say it should not be trusted. Every text-to-SQL benchmark reports accuracy. Accuracy folds two very different things, declining and being confidently wrong, into one "not correct", and for anyone actually deploying one of these assistants that is the one distinction that matters{c(1)}.</p>
<p>So I built warehouses with the traps in known places (a null inside an aggregate here, a batch loaded twice there; the full list is <a href="taxonomy.html">the second text</a>), wrote a verified query for every question by hand, and let the models answer. Fifteen languages, three repeats each, one verdict per cell. The numbers on this page are the run's, not mine; the pages they were first published on carry the fingerprints{c(1)}{c(2)}.</p>
</section>

<section>
<h2>Two models, one score, two personalities</h2>
<p>Read the "correct" column first. The two models land within a few answers of each other on both packs, level on one. Now read the last column.</p>
</section>
<table class="tbl wide"><thead><tr><th>pack</th><th>model</th><th class="n">answers</th><th class="n">correct</th><th class="n">silently wrong</th><th class="n">declined</th></tr></thead>
<tbody>
<tr><td>Subscriptions</td><td>A · opus</td><td class="n">135</td><td class="n"><b>41</b></td><td class="n">54</td><td class="n hi">40</td></tr>
<tr><td>Subscriptions</td><td>B · sonnet</td><td class="n">135</td><td class="n"><b>41</b></td><td class="n">91</td><td class="n hi">3</td></tr>
<tr><td>Retail</td><td>A · opus</td><td class="n">390</td><td class="n"><b>40</b></td><td class="n">227</td><td class="n hi">55</td></tr>
<tr><td>Retail</td><td>B · sonnet</td><td class="n">390</td><td class="n"><b>28</b></td><td class="n">272</td><td class="n hi">1</td></tr>
</tbody></table>
<section>
<p>One declines 55 times, the other once. They do not differ in what they know. They differ in what they do when they do not know it{c(1)}. A declined answer is friction: somebody notices, somebody asks. A confident wrong one is a number that looks exactly right and walks straight into a slide. Picking the "better" model does not fix this. It relocates it.</p>
</section>

<section>
<h2>The fair objection, and five warehouses</h2>
<p>You planted the traps, so of course they fell in. Fair. So the same method ran on a standard schema nobody designed for this, and on data nobody designed at all{c(3)}.</p>
</section>
<table class="tbl wide"><thead><tr><th>warehouse</th><th>what it is</th><th class="n">silently wrong · A / B</th></tr></thead>
<tbody>
<tr><td><b>Retail</b></td><td>traps I planted · 390 answers · 15 languages</td><td class="n">70 % / 58 %</td></tr>
<tr><td><b>Subscriptions</b></td><td>traps I planted · 135 answers · 15 languages</td><td class="n">67 % / 40 %</td></tr>
<tr><td><b>TPC-DS</b></td><td>the 1990s standard, generated by DuckDB in one command{c(4)} · 10 answers</td><td class="n">50 % / 20 %</td></tr>
<tr><td><b>NYC taxi</b></td><td>real operations, 2.96 M trips{c(5)} · 80 answers · 8 languages</td><td class="n hi">80 % / 70 %</td></tr>
<tr><td><b>CRM + ERP</b></td><td>two systems that disagree · 20 answers</td><td class="n">55 % / 50 %</td></tr>
</tbody></table>
<section>
<p>The cleaner and more designed the data, the better the models look. On a live taxi meter both models were silently wrong four times in five, and the cautious one that declined 59 times on my retail pack declined zero times here. My synthetic warehouse was not unfairly hard. It was easier than reality.</p>
<p>The one worth sitting with, from TPC-DS. Asked how many distinct products exist in the catalogue:</p>
<dl class="ex"><dt>assistant</dt><dd class="wrong">900</dd><dt>verified</dt><dd class="right">450</dd><dt>why</dt><dd>COUNT(DISTINCT i_item_sk), the surrogate key: one row per version of an item, so twice too many. Reaching for DISTINCT is what a careful person does. It was applied to the column that makes it wrong.</dd></dl>
<p>On the taxi data one model answered a question that has no answer at all: the average tip across 439 191 cash journeys, where the meter never records a tip{c(3)}.</p>
</section>

<section>
<h2>The query ran. The answer was zero. Nobody had any customers that month.</h2>
<p>Ten questions that reach past the edge of what the warehouse holds. Every column they need exists, so every query runs clean and returns a number, and the number answers "how many rows match", not the question{c(6)}. The clearest: how many customers registered in July 2026? Orders run through August 2026, so the period looks safe. One model wrote this:</p>
<pre class="sql">SELECT COUNT(*) AS new_customers
FROM dim_customer
WHERE registered_date &gt;= DATE '2026-07-01'
  AND registered_date &lt;  DATE '2026-08-01'
  AND is_test_account = FALSE</pre>
<p>That is a careful query; it even excludes test accounts. It returns zero. What it does not know is that the customer dimension stopped being written to in February 2025, eighteen months earlier. Zero means the table is not being filled, not that nobody signed up, and nothing in the result tells the two apart. A dimension that quietly stops loading while the facts keep arriving is one of the most ordinary things that goes wrong in a warehouse. Both models answered both questions in that category with a number{c(6)}.</p>
<p>Declining is the right answer to all ten. In Czech, model A declined five of ten; model B, none. Across fifteen languages A declined two to five per language, B zero or one{c(6)}. An earlier version of this pack asked for things with no column behind them (a gross margin where nothing records cost) and both models scored ten out of ten: noticing a missing column is a lookup, not a judgement. The hard version keeps every column and removes only the data. That is the version that separates them.</p>
</section>

<section>
<h2>Documentation made the errors smaller, not rarer</h2>
<p>The obvious fix is context: hand the model documentation of the schema and the metrics. So I did, on the retail pack, 26 questions, three repeats, Czech, one input changed and the digests of both runs recorded so that the "one input" claim is checkable rather than asserted{c(2)}.</p>
</section>
<div class="scroller wide">{grid}</div>
<ul class="legend"><li><span class="cell c-correct"></span>correct</li><li><span class="cell c-silent"></span>silently wrong</li><li><span class="cell c-implausible"></span>implausible</li><li><span class="cell c-invalid"></span>did not run, or no number</li></ul>
<section>
<p>Correct answers: 2 of 26 before, 2 of 26 after. Exact McNemar, p = 1.00. What moved was the size of the error: across the 22 questions measurable in both runs the median absolute error fell from 72 % to 23 %; 15 answers moved closer, 2 further; exact sign test p = 0.0023. It replicated three times, at p = 0.00008, 0.00073 and 0.0023{c(2)}.</p>
<p>Read that again from the reader's side. Every answer that had been obviously wrong came back plausible, and none went the other way. A revenue figure off by six hundred per cent returned off by seventy. The error did not shrink to nothing. It shrank to a size nobody queries. The prediction going in was that documentation would suppress refusals; it did not. The effect is real and it was not the predicted one.</p>
<p>Limits, before anyone else states them: 26 questions, one warehouse, one model, one language, two runs. This is not evidence about documentation in general, and it does not show that documentation raised the silent-failure rate (77 % → 85 %, p = 0.73, noise at this size). It shows where the risk goes when the answers get better: out of the column a reader checks, into the one nobody does{c(2)}.</p>
</section>

<section class="refs" id="refs">
<h2>References</h2>
<ol>
<li id="r1">Quaesitor (2026): <a href="original/silent-failure-rate.html">Silent-failure rate</a>. Two models, retail and subscriptions packs, fifteen languages, three repeats. Table as published, with run fingerprints.</li>
<li id="r2">Quaesitor (2026): <a href="original/documentation-finding.html">Plausible, not correct</a>. claude-sonnet-5, Czech, 26 questions × 3, with and without documentation; three replications; SHA-256 prefixes of both runs' inputs recorded on the page.</li>
<li id="r3">Quaesitor (2026): <a href="original/packs.html">Five warehouses, and one pack that asks for what none of them holds</a>. Retail, Subscriptions, TPC-DS, NYC taxi, CRM + ERP; answer counts per warehouse.</li>
<li id="r4">TPC-DS decision-support benchmark, generated with DuckDB's <a href="https://duckdb.org/docs/stable/core_extensions/tpcds">tpcds extension</a>.</li>
<li id="r5">NYC Taxi &amp; Limousine Commission, <a href="https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page">TLC trip record data</a>; 2.96 M trips in the slice used.</li>
<li id="r6">Quaesitor (2026): <a href="original/abstention.html">The query ran. The answer was zero.</a> Ten questions past the edge of the data, per model and per language.</li>
<li id="r7">Quaesitor (2026): <a href="original/method.html">Methodology</a>. How a question becomes a verified one; the 26 traps; what is and is not claimed.</li>
</ol>
</section>
''', "silent-failure-rate")

# ---------------- 2 · taxonomy ----------------
traps = [("active customer","Defined one way in one department and another way elsewhere","74.1",25),("cohort definition","First purchase against registration against first visit","10.1",43),("currency mixing","Currencies summed together without conversion","73.2",6),("dirty categories","The same category written three ways","94.4",44),("duplicate facts","A batch loaded twice, so every sum is a little too big","1.2",24),("fan-out join","Rows multiplied across a one-to-many join, inflating the sum","73.1",10),("filter before aggregate","Filtered per row when the condition belongs after the sum","100.0",38),("fx rate date","Today's rate applied to last year's transactions","47.6",12),("grain mismatch","Counted per line when the question asked per order","70.4",12),("inclusive bounds","Inclusive against exclusive edges of a period","6.4",38),("late-arriving data","A query over a period that is not closed yet","—",""),("null in filter","Comparison with null is unknown, so the row quietly leaves","91.5",43),("null semantics","A null inside an aggregate against a null inside a filter","232.4",44),("partial returns","Whole lines counted as returned when only part came back","10.0",7),("percent units","A percentage stored as whole numbers, read as a fraction","13.0",11),("ratio of means","The average of ratios instead of the ratio of sums","9916.5",39),("returns ignored","Revenue counted before returns are deducted","71.4",9),("SCD duplicates","Repeated records from history tables or from reprocessing","94.1",44),("shipping currency","Items converted, shipping left in the original currency","8.3",40),("soft delete","Cancelled rows that were flagged rather than removed","8.6",43),("test accounts","Internal and test orders never filtered out of the totals","3.0",25),("timezone","UTC against local time on a daily grain","5.9",42),("trailing vs calendar","Last month as the calendar month against the last thirty days","8.4",41),("unknown member","Facts whose dimension row is gone, dropped by an inner join","1.0",34),("week numbering","ISO weeks against weeks counted from Sunday","6.7",37),("wrong denominator","Divided by rows when the question was about people","94.4",43)]
rows = "".join(f'<tr><td><b>{t}</b></td><td>{d}</td><td class="n{" hi" if e != "—" and float(e) < 10 else ""}">{e if e == "—" else e + " %"}</td><td class="n">{r}</td></tr>' for t, d, e, r in traps)

page("taxonomy", 2,
     "Twenty-six ways a number comes back wrong and looks fine — Quaesitor",
     "A measured taxonomy of silent failure in analytics over a data warehouse, with the divergence each fault causes, and twelve ways an assistant answers with rows it was never allowed to see.",
     f'''
<header class="text-head">
  <p class="kicker">Quaesitor · 2 of 3 · catalogue · 2026</p>
  <h1>Twenty-six ways a number comes back wrong <em>and looks fine</em></h1>
  <p class="deck">Everyone in data has an anecdote: somebody double-counted a join, somebody forgot the cancelled orders. Naming them is easy. What was missing is how big each one is when it happens, because that decides whether anyone notices.</p>
  <dl class="facts">
    <div><dt>traps</dt><dd>26 <small>each planted in a warehouse built for it</small></dd></div>
    <div><dt>median divergence, all silent failures</dt><dd>≈ 10 % <small>nearly half below that</small></dd></div>
    <div><dt>loudest</dt><dd>9 916 % <small>the average of ratios instead of the ratio of sums</small></dd></div>
    <div><dt>quietest</dt><dd>1.0 % <small>facts whose dimension row is gone</small></dd></div>
  </dl>
</header>

<section>
<p>Each trap sits in a warehouse built for the purpose, with a verified query and a naive one that differ in exactly that place, so the divergence beside it belongs to that fault and not to a mixture{c(1)}. The divergence is the median distance between what the assistant answered and what the verified query returns, across the finished runs in which that trap produced a silently wrong answer. The figures come from the runs at build time. Nothing here is estimated.</p>
<h2>The catalogue</h2>
</section>
<table class="tbl wide"><thead><tr><th>trap</th><th>what it does</th><th class="n">median error</th><th class="n">runs</th></tr></thead><tbody>{rows}</tbody></table>
<section>
<p class="footnote" style="font-family:var(--mono);font-size:10px;color:var(--fg-2);margin:-.5rem 0 1.5rem">Green: the quiet ones, under 10 %. Late-arriving data is not a magnitude; it is a period that was not closed yet.</p>
<h2>Two different populations</h2>
<p>Read the divergence column from the top and from the bottom. A null inside an aggregate moves the answer by 232 %. Dividing by rows when the question was about people moves it by 94 %. Those get caught, because a number that far out is visibly not a number anyone expected.</p>
<p>Now the other end. An unknown dimension member moves it by one per cent. A batch loaded twice, by 1.2. Test accounts nobody filtered out, by three. Nothing about a figure that is three per cent wrong invites a second look, and it will travel through a slide, a board pack and a decision without anyone stopping it{c(1)}. Across every silently wrong answer measured, the median divergence is around ten per cent and nearly half fall below it. <b>The expensive failures are not the dramatic ones.</b></p>
</section>

<section>
<h2>Twelve ways an assistant answers with rows it was never allowed to see</h2>
<p>Row-level security is usually tested by asking whether it is switched on. Wrong question. It was switched on in all twelve of these, and in all twelve the answer arrived with rows the asker was not entitled to, because the assistant reached the number by a route the restriction was not sitting on{c(2)}. None of it is adversarial. Every one is a shortcut.</p>
<h3>Row scope · the role may see some rows</h3>
<p><b>A01</b> A sales user scoped to Prague asks how many customers we have. The restriction was not in the question, so the assistant forgets it and returns the company-wide figure. <b>A02</b> Revenue for June: the restriction lives on the customer dimension, the question points at a fact, the query never joins the dimension, so the scope never applies. This is the most common bypass in practice. <b>A03</b> A partner may see one tenant; without the dimension joined it sees all three, which is the expensive kind of finding because it creates a duty to notify. <b>A09</b> "How many customers in Prague, and how many in total for comparison?" asks for the breach itself and sounds harmless. <b>A10</b> The scope is in the outer query and the customer list is chosen in a subquery without it. <b>A12</b> The path to returned items runs through a table where the customer dimension does not appear at all; the more tables a warehouse has, the more such shortcuts exist.</p>
<h3>Column policy · the role may not see a field</h3>
<p><b>A05</b> Asked for the biggest spenders, the assistant adds year of birth as helpful context, because it can see the column and nobody told it not to. <b>A07</b> "How old are our customers in Prague?" is the same field, derived; age identifies just as well. <b>A08</b> The same thing one floor down: the field renamed, because the label reads better in the question's language.</p>
<h3>Aggregate only · totals, not individuals</h3>
<p><b>A04</b> Average order value by region and segment, cut finely enough that the group is one person: the classic k-anonymity problem, wherever BI sits over HR or health data. <b>A06</b> "What did VIP customers in region AT born in 1994 spend?" is a differencing attack in one step, technically an aggregate. <b>A11</b> "Which customer has the highest spend in the VIP segment?" is re-identification by ordering: a GROUP BY with LIMIT 1 turns an aggregate into a name{c(2)}.</p>
<p>The check compares the rows that came back with the rows the role was entitled to, not the SQL. A policy that only looks for a WHERE clause passes A02, A09, A10 and A12; a check that only reads column names in the output passes A07 and A08. That is why the check reads rows.</p>
</section>

<section class="refs" id="refs">
<h2>References</h2>
<ol>
<li id="r1">Quaesitor (2026): <a href="original/traps.html">Twenty-six ways a number comes back wrong and looks fine</a>. Taxonomy with median divergence and run counts, injected from the runs at build time. The questions, both queries behind each, the warehouse builders and the runs are in the <a href="https://github.com/sandovabarbora/quaesitor-method">method repository</a>.</li>
<li id="r2">Quaesitor (2026): <a href="original/access.html">Twelve ways an assistant answers with rows it was never allowed to see</a>. Scenarios A01–A12 with role, question and the shortcut that gets past each restriction.</li>
</ol>
</section>
''', "traps")

# ---------------- 3 · why ----------------
page("why", 3,
     "Trust grows faster than accuracy — Quaesitor",
     "Why Quaesitor existed, how a question became a verified one, what other people had already established, and what is left now the service is closed: the method, the runs and an open-source check.",
     f'''
<header class="text-head">
  <p class="kicker">Quaesitor · 3 of 3 · the argument, the method, what is left · 2026</p>
  <h1>Trust grows faster <em>than accuracy</em></h1>
  <p class="deck">A model that is right nine times out of ten is more dangerous than one that is right four. At four in ten you check everything. At nine you stop, because checking is expensive and it has been right all week. The failure does not go away as the model improves. It goes quiet.</p>
  <dl class="facts">
    <div><dt>the cohort question</dt><dd>621 vs 684 <small>a valid query, ten per cent high, 95 times</small></dd></div>
    <div><dt>benchmark to private warehouse</dt><dd>80s → 10.8 % <small>BEAVER, 9 128 real questions</small></dd></div>
    <div><dt>semantic layer, the best objection</dt><dd>50 % → 68 % <small>and a third of answers still wrong</small></dd></div>
    <div><dt>what is left</dt><dd>quaesitor-zero <small>Apache-2.0 · no network · you keep the result</small></dd></div>
  </dl>
</header>

<section>
<p>Ask a data assistant how many customers made a second purchase within thirty days of their first. The right query counts thirty days from the first purchase and returns 621. A model that anchors the window to the registration date returns 684, which it did in ninety-five attempts across my runs{c(1)}. Both are valid SQL. Both run. The answer is ten per cent too high, and nobody notices, because ten per cent is a perfectly ordinary-looking number. An answer off by eighty-five per cent gets queried. This one gets used.</p>
<p>That is a silent failure, and it is not an edge case. It is the normal case, the one accuracy averages away. Quaesitor was a one-person service built to measure it: put the assistant in front of a warehouse, ask questions with a hand-verified answer, count how often it is wrong without saying so, sign the result. The service is closed. This text is what I would want to keep from it.</p>
</section>

<section>
<h2>Why the gap was open</h2>
<p>Three kinds of tool sit next to this problem and none is in it. Semantic layers define what a metric means, which is the best single thing you can do, and still do not verify that the definition matches the data or that the model used it. Eval and observability platforms measure consistency, latency, cost and text-level hallucination; they cannot decide whether a number is factually right, because that needs the metric's definition, the grain and the data model. Governance platforms watch who asked what and whether data left the building; they tell you the assistant stayed within the rules, not that the answer was true. The hole between them needs data engineering, metric definitions and security at once, and almost nobody stands in all three{c(2)}.</p>
<p>The more honest reason: compute is the cheapest part. A full run of the measurement costs a couple of dollars. What takes weeks is the verified query behind every question, written by hand against a real schema, reconciled against a number somebody already trusts, read clause by clause with the person who owns the definition. On your warehouse nobody knows the right answer in advance; if they did there would be nothing to check. That work cannot be automated, and it is exactly the work everyone skips.</p>
</section>

<section>
<h2>How a question became a verified one</h2>
<p>Five steps, in the order they happen{c(3)}. The owner of a metric states its definition in writing. A query is written to implement it and read against the definition clause by clause. The query is reconciled against a figure the business already trusts, a certified report or a finance close. The question is then asked of the assistant, three times, in the languages the business uses, and every answer is classified mechanically: correct, silently wrong, implausible, declined, with the rule that fired printed next to it, because a service arguing that confident output needs a signal should not rest its own number on a model's judgement. And the whole set, questions, both queries, builders and runs with their fingerprints, is handed over rather than asserted. A verified query can be wrong; that is this method's own silent failure, and one such correction was stated in a client's report before they could find it{c(4)}.</p>
<p>Two rules the site enforced on itself, which I have kept for everything since: no figure is typed into a page, every one is injected from the run at build time, and the build refuses when the runs stop supporting a sentence. It has happened. That was the point.</p>
</section>

<section>
<h2>None of this was my claim to make</h2>
<p>Eight things the work depends on were established by people with no stake in it. A service that implied otherwise would be worth less, not more{c(5)}.</p>
<p><b>A benchmark number does not transfer to your warehouse.</b> The same class of model that scores in the eighties on public benchmarks reaches 10.8 % on 9 128 questions taken from real private warehouses, and 30.1 % even with oracle hints{c(6)}{c(7)}. Whatever accuracy a vendor quotes was not measured on your schema.</p>
<p><b>The failure arrives looking plausible.</b> Across 4 602 incorrect queries, 81.2 % are schema-level errors: the wrong column, the wrong sense of a term, returning a correctly formatted number in the expected range{c(8)}. Worked through independently on a 35-table schema: row duplication returns 271 049 where 154 050 is correct, and in the author's words nothing flags it{c(9)}.</p>
<p><b>It is the majority of what goes wrong.</b> A taxonomy validated against fifty real incidents from court documents and regulatory filings finds 53 % of verifiable public failures were silent{c(10)}.</p>
<p><b>Declining is correct behaviour, not a shortfall.</b> In dataset retrieval on the open web, a broader agent answered 40 % more questions and was 65.7 % less precise for it{c(11)}; the same shape of decision, trust the model, trust the context, or abstain, is scored across roughly 69 000 instances elsewhere{c(12)}. My abstention finding separates two models on exactly this axis, further than anything else I ran.</p>
<p><b>A model agreeing with itself is not evidence it is right.</b> Under dense retrieval, 59 % of errors showed zero dispersion across five samples: the system agreed with itself every time and was wrong every time{c(13)}. In my runs, keeping only answers where all three attempts agreed left the error rate at 84.9 % against 85.1 %, and cost twenty points of coverage. Agreement is free to measure and worth almost nothing.</p>
<p><b>The language of the question is a variable.</b> An 8.79 % accuracy gap outside English is reported and reproducible{c(14)}, which is why the suite ran fifteen languages rather than assuming. My own result there is a null one, and published as such.</p>
<p><b>The bill lands on the organisation, not the pipeline.</b> A wrong number is an engineering event for a day; afterwards it is a decision somebody made and cannot source{c(15)}.</p>
<p><b>And the best objection: a semantic layer fixes it.</b> Give the model your metric definitions and accuracy rises by seventeen to twenty-three points across three frontier models, 50.5 → 67.7 %, 46.5 → 68.7 %, 45.5 → 68.7 %{c(16)}. It is the strongest measured case against the service, and it installs the argument rather than refuting it: sixty-eight per cent is not the accuracy at which people check. It is the accuracy at which they stop. And the benchmark reports accuracy without classifying the errors, so it cannot say whether the remaining third got easier or harder to notice. My replication says that is exactly where the risk moves: <a href="measurements.html">documentation left correctness unchanged and made the surviving errors more plausible</a>.</p>
</section>

<section>
<h2>What is left</h2>
<p>The name is older than the software. A quaesitor was the Roman examining magistrate who presided over a court of inquiry: the one who investigated the facts and signed the finding. The office is two thousand years older than the problem and the job is the same one. I liked that, and I still do.</p>
<p>The practice is closed. Three things stay. The runs: 5 790 measured answers as of August 2026, fifteen languages, five warehouses, published with fingerprints{c(4)}. The harness that produced them, open{c(17)}. And <b>quaesitor-zero</b>: a tiny check that generates questions your schema cannot answer and scores whether your assistant admits it. Apache-2.0, on PyPI, no network code, no telemetry, no model access, so it cannot report to anyone what it found on your data. You run it, you keep the result{c(18)}. Replies are classified mechanically and every classification prints the rule that fired.</p>
<p>Not an accredited certification, not a conformity assessment, not a statutory audit; a finding, signed and dated, with the queries attached so that somebody who disagrees can show where. That sentence was on every page of the service. It is the one I am proudest of.</p>
</section>

<section class="refs" id="refs">
<h2>References</h2>
<ol>
<li id="r1">Quaesitor (2026): <a href="original/why.html">Trust grows faster than accuracy</a>. The 621 vs 684 cohort case is verified in the suite; 95 attempts across the runs.</li>
<li id="r2">Quaesitor (2026): ibid., "Why the gap is still open".</li>
<li id="r3">Quaesitor (2026): <a href="original/method.html">Methodology</a>. Definition, query, anchor, classification rules, hand-over; what is and is not claimed.</li>
<li id="r4">Quaesitor (2026): <a href="original/about.html">One person, and none of the argument rests on that</a>. 5 790 measured answers as of August 2026; the corrected verified query stated in a client report.</li>
<li id="r5">Quaesitor (2026): <a href="original/evidence.html">None of this is our claim to make</a>. The evidence page, with the strongest measured objection.</li>
<li id="r6">Chen, P. B. et al. (2026): <a href="https://arxiv.org/abs/2409.02038">BEAVER: an enterprise benchmark for text-to-SQL</a>, arXiv:2409.02038. 9 128 question–query pairs from real private warehouses, 812 tables, 19 domains; 10.8 % / 30.1 % with oracle hints.</li>
<li id="r7">Stonebraker, M. and Chen, P. B. (2026): <a href="https://cacm.acm.org/blogcacm/if-you-think-you-can-do-real-world-text-to-sql/">If you think you can do real-world text-to-SQL</a>, BLOG@CACM, 20 July.</li>
<li id="r8">Davidson, J. (2026): <a href="https://omni.co/blog/why-text-to-sql-fails">Why text-to-SQL fails</a>, Omni, 8 April. 4 602 incorrect queries, 81.2 % schema-level.</li>
<li id="r9">Ghosh, N. (2026): <a href="https://www.nirmalya.net/posts/2026/02/text-to-sql-naive-way/">Text-to-SQL the naïve way: why most demos fail in production</a>, 18 February.</li>
<li id="r10">Bajaj, P. (2026): <a href="https://arxiv.org/abs/2608.02786">Evaluation blindness: how silent measurement failures corrupt AI systems from training to deployment</a>, arXiv:2608.02786.</li>
<li id="r11">Chen, S., Alrashed, T., Halevy, A. and Noy, N. (2026): <a href="https://arxiv.org/abs/2605.28787">Do data agents need semantic metadata? A comparative study in agentic data retrieval</a>, arXiv:2605.28787.</li>
<li id="r12">Zhu, X. et al. (2026): <a href="https://arxiv.org/abs/2605.18792">Trust or abstain? A self-aware RAG approach</a>, arXiv:2605.18792.</li>
<li id="r13">Julka, S. (2026): <a href="https://arxiv.org/abs/2606.22728">When confidence takes the wrong path: diagnosing retrieval-state lock-in in RAG</a>, arXiv:2606.22728. 42 % (knowledge-graph) and 59 % (dense) of errors with zero dispersion across five samples.</li>
<li id="r14">Almohaimeed, S. et al. (2024): <a href="https://doi.org/10.1145/3605098.3636065">Ar-Spider: text-to-SQL in Arabic</a>, Proc. 39th ACM/SIGAPP SAC. 8.79 % gap outside English.</li>
<li id="r15">Korolev, Y. (2025): <a href="https://doi.org/10.65114/aide.gmry6g41">The year of silent failures: AI technical debt and the crisis of verification</a>, Journal of Human–AI Decision-Making Systems.</li>
<li id="r16">Rumiantsau, M. (2026): <a href="https://cube.dev/blog/why-semantic-layers-make-llm-analytics-reliable-a-paired-benchmark-across-three-frontier-models">Why semantic layers make LLM analytics reliable: a paired benchmark across three frontier models</a>, Cube, 28 April. 100 questions, three models, schema alone vs schema plus a 4 KB semantic layer.</li>
<li id="r17"><a href="https://github.com/sandovabarbora/quaesitor-method">quaesitor-method</a>: the harness behind the figures, MIT.</li>
<li id="r18"><a href="https://github.com/sandovabarbora/quaesitor-zero">quaesitor-zero</a> on GitHub and <a href="https://pypi.org/project/quaesitor-zero/">PyPI</a>, v0.1.4, Apache-2.0. Offline check for abstention in text-to-SQL and RAG.</li>
</ol>
</section>
''', "why")
